name: Build and Push Multi-Platform Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base_image: debian:stable-slim
            dockerfile: ./Dockerfile
            tag: debian
          - base_image: ubuntu:22.04
            dockerfile: ./Dockerfile
            tag: ubuntu
          - base_image: alpine:latest
            dockerfile: ./Dockerfile.alpine
            tag: alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            fugginold/adsb-feeder:${{ matrix.tag }}
            fugginold/adsb-feeder:latest
